### ISSUE TITLE
Read Time Out and Connection Refused

### ISSUE THREAD

**Issue by MordecaiN7** [solita/clamav-rest#34]
Hello, 
I have the in the Topic named problems and need a little bit help. 
We are using the official clamAV version in a Docker Container from clamav/clamav an the REST-API from Lokori. 
https://hub.docker.com/r/lokori/clamav-rest/
He refers to you. 

We start ClamAV out of a docker-compose.yml 
It ist the following code

version: "3.2"

```
services:
  clamav-server:
    restart: unless-stopped
    image: clamav/clamav
    #image: mkodockx/docker-clamav
  clamav-rest:
    image: lokori/clamav-rest
    restart: unless-stopped
    links:
      - clamav-server
    environment:
      CLAMD_HOST: clamav-server
    ports:
      - 8081:8080
    logging:
      options:
        max-size: 50m
```
We take the clamav/clamav because it runs on a newer version of ClamAV 

When you see a an mistake in our .yml file pls tell me bur thats not the reason why i contact you. :-) 

In the log files i see very often the following errors:

![Bildschirmfoto 2021-09-16 um 11 09 51](https://user-images.githubusercontent.com/90382982/133618838-98fa0d52-060a-4bb1-9a52-d384b9905b39.png)
![Bildschirmfoto 2021-09-16 um 11 09 25](https://user-images.githubusercontent.com/90382982/133618861-bbe07234-85f6-427a-85ad-979189fa46a1.png)

I hope you can help me to find out where is my problem. 

I was thinking about it to mount a volume in our docker-compose.yml with the clamd.config bur i think also that dosn´t make sense because it is an Clam-Rest problem. Maybe :-) 
Or is there a way to mount something like a clam-rest.config if there is such a thing.
